apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: devops-mongo
spec:
  serviceName: "devops-mongo-service"
  replicas: 1
  selector:
    matchLabels:
      app: devops-mongo
  template:
    metadata:
      labels:
        app: devops-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:5.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi