apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-production

bases:
- ../../base
- ../../mongodb

resources:
- ingress.yaml

images:
- name: devops-app
  newName: my-registry/devops-app
  newTag: v1.0.0

configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - NODE_ENV=production

replicas:
- name: devops-app
  count: 3